baseURL = "https://yaahi.github.io/"
languageCode = "en-us"
title = "याहि!!"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/yaahi/yaahi.github.io/edit/master/content/"
  contactLink = "https://github.com/yaahi/yaahi.github.io/issues/new"
  env = "production"
  disqusShortcode = "yaahi-projects-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
   unsafe = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2
